---
apiVersion: v1
kind: Template
metadata:
  labels:
    project: quiver
    version: 1.0.1
  name: quiver-support
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: quiver
    name: fedora
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: fedora:29
      from:
        kind: DockerImage
        name: fedora:29
      name: "29"
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: quiver
      version: 1.0.1
    name: quiver
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: quiver
      version: 1.0.1
    name: quiver
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: quiver:latest
    runPolicy: Serial
    source:
      contextDir: /packaging/openshift
      git:
        uri: https://github.com/ssorj/quiver.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: fedora:29
      type: Docker
    triggers:
    - type: ConfigChange
