---
apiVersion: v1
kind: Template
metadata:
  labels:
    project: quiver
    version: 1.0.0
  name: quiver-pod
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: quiver
      version: 1.0.0
    name: ${POD_NAME}
  spec:
    containers:
    - command: ${{DOCKER_CMD}}
      env:
      - name: KUBERNETES_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: JAVA_OPTS
        value: ${JAVA_OPTS}
      image: ${DOCKER_IMAGE}
      imagePullPolicy: Always
      name: quiver
      securityContext:
        privileged: false
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - quiver
        from:
          kind: ImageStreamTag
          name: quiver:latest
      type: ImageChange
parameters:
- name: POD_NAME
  generate: expression
  from: quiver-[a-z0-9]{5}
- name: DOCKER_IMAGE
  required: true
- name: DOCKER_CMD
  required: true
- name: JAVA_OPTS
  required: false

