#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import with_statement

import time

from plano import *

impls = (
    "qpid-jms",
    "qpid-messaging-cpp",
    "qpid-messaging-python",
    "qpid-proton-python",
)

port = ARGS[1]
messages = ARGS[2]    

script = file_name(ARGS[0])
timestamp = time.strftime('%Y-%m-%d', time.localtime())
output_dir = "{}-{}-{}".format(script, port, timestamp)

remove(output_dir)
make_dir(output_dir)

with working_dir(output_dir):
    for impl in impls:
        command = "quiver-launch //localhost:{}/q0 --impl {} -n {} > {}.txt"

        try:
            call(command.format(port, impl, messages, impl))
        except KeyboardInterrupt:
            raise
        except:
            pass
            
print(output_dir)
        
for name in (list_dir(output_dir)):
    print("  {}".format(name))
