#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

set -ex

RUN_DEPS="java-1.8.0-openjdk nodejs python python3 python-numpy python3-numpy python-qpid-messaging python3-qpid-proton qpid-cpp-client qpid-proton-c qpid-proton-cpp unzip xz"
BUILD_DEPS="gcc-c++ java-1.8.0-openjdk-devel maven make qpid-cpp-client-devel qpid-proton-c-devel qpid-proton-cpp-devel"

dnf -y install $RUN_DEPS $BUILD_DEPS

make install PREFIX=/usr

#dnf -y remove $BUILD_DEPS

dnf clean all

rm -rf $HOME/.m2
