#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
b# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def main():
    try:
        check_header("qpid/messaging/Connection.h")
    except CalledProcessError:
        exit(1)

def check_header(header):
    source_file = make_temp_file(extension=".cpp")
    output_file = make_temp_file()
    source = "#include <{}>\n int main() {{ return 1; }}\n".format(header)

    write(source_file, source)

    with open(NULL_DEV, "w") as out:
        call("g++ {} -o {}", source_file, output_file, output=out)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
