#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

import argparse
import os
import shutil
import sys

def main():
     parser = argparse.ArgumentParser()

     parser.add_argument("input_file", metavar="INPUT-FILE")
     parser.add_argument("output_file", metavar="OUTPUT-FILE")
     parser.add_argument("-a", "--attribute", metavar="NAME=VALUE", action="append")

     args = parser.parse_args()

     output_dir = os.path.split(args.output_file)[0]

     if not os.path.exists(output_dir):
          os.makedirs(output_dir)

     with open(args.input_file, "r") as f:
          content = f.read()

     for attribute in args.attribute:
          name, value = attribute.split("=", 1)
          content = content.replace("@{}@".format(name), value)

     with open(args.output_file, "w") as f:
          f.write(content)

     shutil.copymode(args.input_file, args.output_file)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
