#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import os
import shutil
import sys

try:
     input_file, output_file, name, value = sys.argv[1:]
except:
     exit("Usage: configure-file INPUT-FILE OUTPUT-FILE NAME VALUE")

assert os.path.isfile(input_file)
     
with open(input_file, "r") as f:
     content = f.read()

content = content.replace("@{}@".format(name), value)

parent_dir = os.path.dirname(output_file)

if not os.path.exists(parent_dir):
     os.makedirs(parent_dir)

assert os.path.isdir(parent_dir)

with open(output_file, "w") as f:
     f.write(content)

shutil.copymode(input_file, output_file)
