#!/usr/bin/python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from quiver.common import *

test_template = """
def test_pair_{sender_impl_symbol}_to_{receiver_impl_symbol}(session):
    _test_pair("{sender_impl}", "{receiver_impl}")
"""

for sender_impl in AMQP_ARROW_IMPLS:
    print("# {}".format(sender_impl))
    print()
    
    for receiver_impl in AMQP_ARROW_IMPLS:
        sender_impl_symbol = sender_impl.replace("-", "_")
        receiver_impl_symbol = receiver_impl.replace("-", "_")
        
        print(test_template.format(**locals()).strip())
        print()
