#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

set -eu

# until nc localhost $port 2> /dev/null < /dev/null; do
#     sleep 0.1
# done

if (( $# == 1 )); then
    COUNT=$1
else
    COUNT=1000
fi

PORT=$(python -S -c "import random; print random.randrange(49152, 65535)")
ADDRESS=//localhost:$PORT/q0

quiver --verbose --server receive $ADDRESS -n $COUNT &
quiver --verbose send $ADDRESS -n $COUNT
wait

# XXX _qpid_messaging.NotFound: No such target : q0
#quiver --server receive $ADDRESS -n $COUNT &
#quiver send --impl qpid-messaging-python $ADDRESS -n $COUNT
#wait

# quiver --server send $ADDRESS -n $COUNT &
# quiver receive $ADDRESS -n $COUNT
# wait

# quiver --server send $ADDRESS -n $COUNT &
# quiver receive --impl qpid-messaging-python $ADDRESS -n $COUNT
# wait
