#!/usr/bin/python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def main():
    set_message_threshold("warn")

    call_and_print_on_error("quiver q0 --quiet --init-only")
    call_and_print_on_error("quiver-arrow send //localhost:12345/a/b/c --init-only")
    call_and_print_on_error("quiver-bench --init-only --output {}", make_temp_dir())
    call_and_print_on_error("quiver-launch q0 --init-only")
    call_and_print_on_error("quiver-server q0 --init-only")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
