#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def run_test(args, intermediated=True):
    port = random_port()

    if intermediated:
        server = start_process("quiver-server --quiet //127.0.0.1:{}/q0", port)

    try:
        call_and_print_on_error("quiver //127.0.0.1:{}/q0 {}", port, args)
    finally:
        if intermediated:
            stop_process(server)

def main():
    call_and_print_on_error("quiver --help")
    call_and_print_on_error("quiver q0 --init-only")

    run_test("-m 10k --verbose")
    run_test("--arrow qpid-jms -m 1")
    run_test("--arrow vertx-proton -m 1")
    run_test("--arrow rhea -m 1 --peer-to-peer", intermediated=False)
    run_test("--arrow qpid-proton-python -m 1 --peer-to-peer", intermediated=False)

    # XXX Fails with javax.jms.JMSException: the txn-id field is mandatory
    #run_test("--arrow qpid-jms -m 1 --transaction-size 10 --verbose")

    notice("PASSED")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
