#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def test_impl(impl):
    port = random_port()
    ready_file = make_temp_file()
    server = start_process("quiver-server //127.0.0.1:{}/q0 --impl {} --ready-file {}", port, impl, ready_file)

    for i in range(30):
        if read(ready_file) == "ready\n":
            break

        sleep(1)

    try:
        call("quiver //127.0.0.1:{}/q0 -m 1", port)
    finally:
        stop_process(server)

def main():
    test_impl("builtin")

    # XXX Needs port assignability
    #if which("activemq"):
    #    test_impl("activemq")

    #if which("artemis"):
    #    test_impl("activemq-artemis")

    #if which("qpidd"):
    #    test_impl("qpid-cpp")

    #if which("qdrouterd"):
    #    test_impl("qpid-dispatch")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
