#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import with_statement

import subprocess
import sys
import time

from plano import *

def test(client, messages):
    executable = join(home_dir(), "artemis", "bin", "artemis")
    queue_type = "core-queue"
    
    if client in ("activemq-artemis-jms", "activemq-jms"):
        queue_type = "jms-queue"
    
    server = start_process("{} run", executable)

    sleep(5)

    cmd = "{} destination create --name q0 --type {}"
    call(cmd, executable, queue_type)
    
    cmd = "quiver //localhost/q0 --impl {} -m {} --debug"
    call(cmd, client, messages)

    stop_process(server)

if len(ARGS) != 3:
    print("Usage: {} CLIENT MESSAGES".format(program_name()))
    exit("Wrong arguments")
    
if not is_dir(join(home_dir(), "artemis")):
    exit("I need an artemis instance installed at $HOME/artemis")

# XXX Also make sure port 61616 is free
    
client = ARGS[1]
messages = ARGS[2]

try:
    test(client, messages)
except KeyboardInterrupt:
    pass
