#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def run_test():
    port = random_port()
    server = start_process("quiver-server --quiet //127.0.0.1:{}/q0", port)

    try:
        wait_for_port(port)
        call_and_print_on_error("quiver-launch //127.0.0.1:{}/q0 --count 1 --options \"-m 1\" --verbose", port)
    finally:
        stop_process(server)

def main():
    call_and_print_on_error("quiver-launch q0 --init-only")
    call_and_print_on_error("quiver-launch --sender-options=\"-m 1\" --receiver-options=\"-m 1 --server --passive\" //127.0.0.1:{}/q0", random_port())

    run_test()

    notice("PASSED")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
