#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def run_test(peer_to_peer=False):
    temp_dir = make_temp_dir()

    args = [
        "quiver-bench",
        "-m", "1",
        "--exclude-senders", "qpid-messaging-python",
        "--include-servers", "builtin",
        "--exclude-servers", "none",
        "--verbose",
        "--output", temp_dir,
    ]

    if peer_to_peer:
        args += ["--peer-to-peer"]

        # XXX Trouble with this one
        args += ["--exclude-receivers", "qpid-proton-cpp"]
    else:
        args += ["--client-server"]

    call(args)

def main():
    call_and_print_on_error("quiver-bench --help")
    call_and_print_on_error("quiver-bench --init-only")

    run_test(peer_to_peer=False)
    run_test(peer_to_peer=True)

    notice("PASSED")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
