#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import with_statement

import subprocess
import sys
import time

from plano import *

config_template = """
router {
    mode: standalone
    id: test-client-with-qdrouterd-1
}

listener {
    host: ::
    port: @port@
    authenticatePeer: off
    saslMechanisms: ANONYMOUS
}
"""
        
def test(client, messages):
    port = random_port()

    config = config_template.replace("@port@", str(port))
    config_file = write_temp("qdrouterd-config", config)
    server = start_process("qdrouterd --config {}", config_file)

    cmd = "quiver //localhost:{}/q0 --impl {} -n {} --debug"
    call(cmd, port, client, messages)

    stop_process(server)

if len(ARGS) != 3:
    print("Usage: {} CLIENT MESSAGES".format(program_name()))
    exit("Wrong arguments")
    
client = ARGS[1]
messages = ARGS[2]

try:
    test(client, messages)
except KeyboardInterrupt:
    pass
