#!/usr/bin/python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def main():
    enable_logging(level="warn")
    impls = ["c", "python", "cpp"]
    pairs = [(s,r) for s in impls for r in impls]
    # This requires a router or broker to be running
    for s, r in pairs:
        cmd = "quiver --peer-to-peer -m 10 --sender %s --receiver %s /x" % (s, r)
        print("==== %s" % cmd)
        try:
            call(cmd, quiet=True)
        except:
            pass
    # TODO aconway 2018-11-01: use --peer-to-peer for this test, the C++ binding
    # has problems running in passive receiver mode.

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
